### ISSUE TITLE
Improve navigation by using Nextjs Link component

### ISSUE THREAD

**Issue by inezabonte** [nkowaokwu/igbo_api#464]
**Describe the bug**
Currently the navigation between pages is linked using the basic html anchor tags which loads the page a fresh
whenever you click the link and it's kinda slow

**To Reproduce**
1. Go to the homepage
2. Try navigating between the following pages [homepage,about, signup]

**Expected behavior**
Instant page load due to the use of Link component from Nextjs

**Comment by inezabonte** [comment]
I'd be happy to work on this. :)

**Comment by ijemmao** [comment]
@inezabonte this looks great! lmk if you need any more context on this!

**Comment by ijemmao** [comment]
I'm closing this ticket since it's a bit outdated, we're working on a new website design if you would like to be a part of that project @inezabonte
