### ISSUE TITLE
Create `tsconfig.json` file

### ISSUE THREAD

**Issue by ijemmao** [nkowaokwu/igbo_api#614]
**Is your feature request related to a problem? Please describe.**
We want to convert the Igbo API codebase to start using Typescript.

**Describe the solution you'd like**
Create a new `tsconfig.json` file that will establish the base configuration for our TS codebase.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by Aditya062003** [comment]
I would be interested in making a contribution to this issue. Could you please assign it to me?

**Comment by Ebugo** [comment]
I'd like to take this up. @ijemmao

**Comment by ijemmao** [comment]
great 👏🏾@Ebugo
