### ISSUE TITLE
Replace the NG on the navbar with GitHub icon

### ISSUE THREAD

**Issue by Superfly101** [nkowaokwu/igbo_api#622]
**Describe the bug**
On the Navbar of the documentation site, clicking on the NG icon leads to the igbo_api GitHub repo

**To Reproduce**
1. Go to the [docs](https://igboapi.com/docs)
2. Click on 'NG' present at the top navbar

**Expected behavior**
The GitHub logo should be in place of the NG, finding a link to this repo was not as obvious as it should be

**Screenshots**
<img width="975" alt="Screenshot 2023-05-06 190627" src="https://user-images.githubusercontent.com/68870695/236648671-d7d6b72b-1b24-4ced-b0ae-da5e396dc58d.png">

**Desktop (please complete the following information):**
 - OS: [Windows 11]
 - Browser [Chrome]

**Comment by Superfly101** [comment]
If this issue is valid, I would love to be assigned to it. This should be an easy fix with Nextra

**Comment by ijemmao** [comment]
excited to see this fix 🔥
