### ISSUE TITLE
Convert `src/models` files from JS to TS

### ISSUE THREAD

**Issue by ijemmao** [nkowaokwu/igbo_api#659]
**Is your feature request related to a problem? Please describe.**
We want to have all our `src/models/plugins/*` and `src/models/*` files converted to TS.

[Plugins file to convert](https://github.com/nkowaokwu/igbo_api/tree/master/src/models/plugins)
[Models files to convert](https://github.com/nkowaokwu/igbo_api/tree/master/src/models)

**Describe the solution you'd like**
Convert the mentioned files into TS. None of these files should have any logical changes, just changing them from JS to TS. Prettier will run and format the file which is okay.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by mysticwillz** [comment]
Hey i want to work on this, can you assign it to me?.

**Comment by harryportal** [comment]
Hi, I would love to work on this!

**Comment by chinedu360** [comment]
@ijemmao assign this task to me, be done before the ending of tomorrow

**Comment by ijemmao** [comment]
@harryportal @chinedu360 i assigned to both of you, looking forward to your PRs!

**Comment by chinedu360** [comment]
@ijemmao i ran into lots of issues trying to get the application setup. I am on a Mac M1
<img width="959" alt="Screenshot 2023-06-23 at 05 39 25" src="https://github.com/nkowaokwu/igbo_api/assets/46059757/e0c37b96-83ed-4811-86bf-b092e111bcea">

**Comment by ijemmao** [comment]
@chinedu360 the command `yarn start:database` failed which is responsible for starting up the MongoDB instance. you might have something already running on port :27017 - can you confirm that after closing whatever is running on that port that you're still unable to start the project?

**Comment by chinedu360** [comment]
@ijemmao i think that could be the issue. I will check and revert back.
