### ISSUE TITLE
Convert `src/routers` to TS

### ISSUE THREAD

**Issue by ijemmao** [nkowaokwu/igbo_api#660]
**Is your feature request related to a problem? Please describe.**
Convert `src/routers` to TS.

**Describe the solution you'd like**
Convert `src/routes` to TS.

**Considerations**
* There shouldn't be any logical changes to these files.
* Prettier will automatically format these files which is okay.
* If these files require types or interfaces, please create new types and interfaces to strongly type functions, objects, etc.

[Router files to convert to TS](https://github.com/nkowaokwu/igbo_api/tree/master/src/routers)

**Describe alternatives you've considered**

**Additional context**

**Comment by IAmYoungbossy** [comment]
Hello @ijemmao I would love to take this.

**Comment by ijemmao** [comment]
@IAmYoungbossy all yours!
