### ISSUE TITLE
Convert `src/services`

### ISSUE THREAD

**Issue by ijemmao** [nkowaokwu/igbo_api#661]
**Is your feature request related to a problem? Please describe.**
Convert `src/services` to TS

**Describe the solution you'd like**
Convert `src/services` to TS. There shouldn't be any logical changes to these files. Prettier will automatically format these files which is okay.

[Files to change](https://github.com/nkowaokwu/igbo_api/tree/master/src/services_

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by Dhaxor** [comment]
Hello, I'm interested in taking this up.

**Comment by ijemmao** [comment]
@Dhaxor assigned to you
