### ISSUE TITLE
Convert `src/pages` to TS

### ISSUE THREAD

**Issue by ijemmao** [nkowaokwu/igbo_api#662]
**Is your feature request related to a problem? Please describe.**
Convert `src/pages` top-level files (this means ignoring the files within the nested directories like `assets`, `components`, and `docs`) to TS

**Describe the solution you'd like**
Convert `src/pages` to TS

[Convert the files directly within `src/pages` and none in the nested directories](https://github.com/nkowaokwu/igbo_api/tree/master/src/pages)

**Considerations**
* Please introduce new types or interfaces to correctly type these files.
* Don't introduce any logical changes to these files.
* Prettier will run automatically which is okay.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by anmol111pal** [comment]
Hey, I wish to work on this issue.
Please assign this to me. @ijemmao

**Comment by ijemmao** [comment]
all yours! @anmol111pal

**Comment by kenneropia** [comment]
I’m interested in working on this. is there anything im supposed to be aware of that hasn’t be explicitly said?

**Comment by ijemmao** [comment]
@kenneropia nope, just convert the files to TS and introduce any necessary types/interfaces to ensure that the files are fully typed

**Comment by kenneropia** [comment]
okay 👍🏾

**Comment by kenneropia** [comment]
just started working on this, i haven't had a free day in a while. I can't find any contribution guide, so I just make a fork and work on a branch

**Comment by JoannaEbreso** [comment]
I am interested in working on this.

**Comment by ijemmao** [comment]
@JoannaEbreso I just assigned this to you

**Comment by promiseNwafor** [comment]
@ijemmao I checked and it seems like the files have all been converted to TS. Let me know if there's something else to do here.
