### ISSUE TITLE
Make tsconfig strict

### ISSUE THREAD

**Issue by Faithfinder** [nkowaokwu/igbo_api#663]
![Screenshot_20230620-130027](https://github.com/nkowaokwu/igbo_api/assets/25051063/a868596d-14f1-40e4-aa63-ddbb87c8247f)
Sorry for a short issue, but I was just passing by, not really interested in your project. Just randomly saw that message on Twitter and decided to give advice nobody asked for =P

**Comment by dhruvdabhi101** [comment]
I would love to work on this issue

**Comment by Toyin5** [comment]
Assign this to me please

**Comment by ijemmao** [comment]
@dhruvdabhi101 it's yours
