### ISSUE TITLE
Rectifying the Copyright Year and Name of Copyright Owner

### ISSUE THREAD

**Issue by mustafaalameen** [nkowaokwu/igbo_api#664]
![Screenshot (630)](https://github.com/nkowaokwu/igbo_api/assets/70868527/63a68a36-cfa7-4a2a-9aec-15da01a020b4)

I intend to change [YYYY] to the copyright year and the [name of the copyright owner] to the copyright holder.

I will need the necessary information to change it and would like to know the project's goal in case a better license than Apache 2.0 can be advised.

**Comment by ijemmao** [comment]
2023 - Nkọwa okwu

thanks @mustafaalameen
