### ISSUE TITLE
Typo error?

### ISSUE THREAD

**Issue by Toyin5** [nkowaokwu/igbo_api#665]
**Describe the bug**
A typographical error on the homepage

**To Reproduce**
1. Go to the homepage
2. Scroll down

**Expected behavior**
It should be **Nsibidi writing system was ....** without the _is_

**Screenshots**
![Screenshot_20230620_215521_Chrome.png](https://github.com/nkowaokwu/igbo_api/assets/40214690/fba7a12f-71fe-427f-9ae7-65a74ca06863)

**Comment by ijemmao** [comment]
@Toyin5 great catch. It should be:

Nsịbịdị is a writing system created in Nigeria.

**Comment by Toyin5** [comment]
Can I work on it?

**Comment by ijemmao** [comment]
> Can I work on it?

all yours!
