### ISSUE TITLE
Convert `src/pages/components` to TS

### ISSUE THREAD

**Issue by ijemmao** [nkowaokwu/igbo_api#669]
**Is your feature request related to a problem? Please describe.**
Convert `src/pages/components` to TS

**Describe the solution you'd like**
Convert [`src/pages/components` components](https://github.com/nkowaokwu/igbo_api/tree/master/src/pages/components) to TS

Avoid making any logical changes while converting these files. Some of these files will need new types and interfaces, please add them wherever necessary. Prettier will format files which is okay.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by sir-radar** [comment]
I will be working on this issue

**Comment by ijemmao** [comment]
@sir-radar all yours!
