### ISSUE TITLE
Convert `src/controllers/utils` to TS

### ISSUE THREAD

**Issue by ijemmao** [nkowaokwu/igbo_api#671]
**Is your feature request related to a problem? Please describe.**
Convert `src/controllers/utils` to TS

**Describe the solution you'd like**
Conver [`src/controllers/utils`](https://github.com/nkowaokwu/igbo_api/tree/master/src/controllers/utils) to TS

Avoid making logical changes to these files. Some of these files will need new types or interfaces, add them whenever necessary. Prettier will format these files which is okay.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by Harshal662** [comment]
There are 3 files in .js format so all the 3 files should be converted to TS?

**Comment by ijemmao** [comment]
@Harshal662 that's correct

i assigned to both of you @Dhaxor @Harshal662
