### ISSUE TITLE
Convert top-level files in `src/controllers` to TS

### ISSUE THREAD

**Issue by ijemmao** [nkowaokwu/igbo_api#672]
**Is your feature request related to a problem? Please describe.**
Convert top-level JS files in `src/controllers` to TS

**Describe the solution you'd like**
Convert [these top-level files](https://github.com/nkowaokwu/igbo_api/tree/master/src/controllers) (ignoring any files in utils) to TS

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by Stancobridge** [comment]
Am working on this issue @ijemmao

**Comment by RichiieStowie** [comment]
I would love to work on this issue @ijemmao. pls assign to me

**Comment by ijemmao** [comment]
@Stancobridge @RichiieStowie i assigned to both of you!

**Comment by IfyNdu** [comment]
I am happy to pick up this issue since there isn't much activity @ijemmao
