### ISSUE TITLE
Convert `src/APIs` to TS

### ISSUE THREAD

**Issue by ijemmao** [nkowaokwu/igbo_api#673]
**Is your feature request related to a problem? Please describe.**
Convert `src/APIs` to TS

**Describe the solution you'd like**
Convert [`src/APIs`](https://github.com/nkowaokwu/igbo_api/tree/master/src/APIs) to TS 

Avoid making logical changes to these files. These files may need new types or interfaces, so add them whenever necessary. Prettier will format these files which is okay.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by shaikahmadnawaz** [comment]
Can I work on this issue?

**Comment by zanio** [comment]
Can I also work on this @ijemmao

**Comment by shaikahmadnawaz** [comment]
> Can I also work on this @ijemmao

Yes @zanio

**Comment by ijemmao** [comment]
This ticket has been addressed! Thanks for calling this out @zanio
