### ISSUE TITLE
Typo in Code of Conduct.

### ISSUE THREAD

**Issue by rohit-rambade** [nkowaokwu/igbo_api#678]
**Describe the bug**
there is a double comma after "homepage" in the Attribution
**To Reproduce**
1. Go to 'Docs'
2. Click on 'Code of Conduct'
3. Scroll down to 'Attribution'

**Screenshots**
![image](https://github.com/nkowaokwu/igbo_api/assets/86614477/32d5ada6-b398-437b-add4-8fa63c927ab7)

**Expected behavior**
![image](https://github.com/nkowaokwu/igbo_api/assets/86614477/9b94de9a-dea4-499d-8894-720a2cb178ce)

**Comment by CYBWEBALI** [comment]
Can I work on this issue?

**Comment by Pavan-Nagulla** [comment]
I can't see the double comma after " homepage " in Attribution. It was already solved the issues.

**Comment by CYBWEBALI** [comment]
![image](https://github.com/nkowaokwu/igbo_api/assets/88965204/682c3def-e0b5-499d-81c1-c54047db47f5)

It is there.

**Comment by Pavan-Nagulla** [comment]
Thanks bro !! Got it

**Comment by ijemmao** [comment]
thanks @CYBWEBALI just assigned to you

**Comment by CYBWEBALI** [comment]
Done PR #684 .
