### ISSUE TITLE
Update Slack community count from 150+ to 230+

### ISSUE THREAD

**Issue by ijemmao** [nkowaokwu/igbo_api#681]
**Is your feature request related to a problem? Please describe.**
Update our total community size from 150+ to 230+

**Describe the solution you'd like**
Update our total Slack community size from 150+ to 230+

**Describe alternatives you've considered**
N/A

**Additional context**
![image](https://github.com/nkowaokwu/igbo_api/assets/16169291/3551f013-5bb5-4b73-8011-9180bbce9266)
_Change this from 150+ to 230+_

**Comment by tarunsamanta2k20** [comment]
I'd like to work on it.

**Comment by ijemmao** [comment]
assigned to both of you @rohit-rambade @tarunsamanta2k20
