### ISSUE TITLE
Syncing GitHub Star Count on Homepage

### ISSUE THREAD

**Issue by kingdanie** [nkowaokwu/igbo_api#690]
**Is your feature request related to a problem? Please describe.**
automatically update the GitHub star on websites homepage to match Start count of this GitHub's repo. 

**Describe the solution you'd like**
To automatically sync the star count of this GitHub's repo with a count displayed on homepage (utilising the GitHub API). By implementing a server-side function, we can fetch the star count dynamically. This will enable auto update to the current star count of the repository on your homepage.

**Describe alternatives you've considered**
1. Using third party libraries such as  Shields.io or Badgen.
2. Github web hook.

**Additional context**
<img width="329" alt="Screenshot 2023-06-22 at 15 17 08" src="https://github.com/nkowaokwu/igbo_api/assets/52611355/a65a4df8-d412-4c97-9f74-a4e9956c4f8e">

**Comment by peculiarrichard** [comment]
i want to work on this, could you assign it to me?

**Comment by ijemmao** [comment]
@kingdanie this functionality already exists for the site - we don't hard code the stars count and we rely on the GitHub API to get this number. I'll close this issue, but feel free to re-open it if there's more context you would like to add!
