### ISSUE TITLE
create Login Form component

### ISSUE THREAD

**Issue by davydocsurg** [nkowaokwu/igbo_api#695]
Create a login form component 
The form should have the following:
- email field
- password field
- forgot password link (this should lead to nowhere because it doesn't exist yet)

**Comment by kingdanie** [comment]
I think this is a duplicate issue, has it is already been discussed in  #603

**Comment by cindyeme** [comment]
Has this been worked on already? @davydocsurg

**Comment by kingdanie** [comment]
Yes pls.

**Comment by ijemmao** [comment]
@davydocsurg @cindyeme @kingdanie i believe this PR is already open to create the login page that, from what i can tell, also includes a UI login component -https://github.com/nkowaokwu/igbo_api/pull/698

that login component doesn't talk to the backend yet - that's definitely a follow up ticket
