### ISSUE TITLE
Contact & Email Text overlapping 

### ISSUE THREAD

**Issue by rohit-rambade** [nkowaokwu/igbo_api#696]
**Describe the bug**
On The resolution 375x667 ( Iphone SE ) Contact and Email text are overlapping . 
**To Reproduce**
1. Go to 'https://igboapi.com/about'
2. Switch to Mobile View & Select Iphone SE
3. Scroll down little bit

**Screenshots**
![image](https://github.com/nkowaokwu/igbo_api/assets/86614477/bc84ca3e-96cd-44d6-8788-312ca959baf3)

**Expected behavior**
![image](https://github.com/nkowaokwu/igbo_api/assets/86614477/aec5b6cc-9da5-4929-912a-e97ed4a0e3ea)

**Comment by ijemmao** [comment]
@Teea-dev hey! open-source repos typically have a CONTRIBUTION.md guide that you can read through to learn how to get started - https://github.com/nkowaokwu/igbo_api/blob/master/.github/CONTRIBUTING.md

I've assigned this issue to you! good luck and feel free to add more comments to ask clarifying questions

**Comment by rohit-rambade** [comment]
@ijemmao I Already Submitted PR for this. Please Look into it .

**Comment by Teea-dev** [comment]
Hi, good afternoon  @ijemmao I am having issues installing the project after I cloned it to my machine. There seems to be some conflict between material-ui/core and the version of react. I don't know if you noticed but what do you suggest I do??
