### ISSUE TITLE
Define the /login business logic

### ISSUE THREAD

**Issue by davydocsurg** [nkowaokwu/igbo_api#715]
Define the user authentication flow. Please take inspiration from existing code snippets like `validateApiKey.js` so you can see how to define an Express middleware.

The goal of this ticket: update the `/login` endpoint so that when we make a `POST` request, we are able to authenticate the user and provide the expected response object

**Comment by woodmark-dev** [comment]
Is this taken yet? I'd like to work on this if it's still open.

**Comment by ijemmao** [comment]
@davydocsurg is the business logic that's needed for this ticket to start included? if so, I can assign @woodmark-dev

**Comment by davydocsurg** [comment]
@ijemmao Yeah, but it's blocked by #704

**Comment by ijemmao** [comment]
I think this should be a GET request instead of a POST request. Why did you decide to go with POST?

**Comment by davydocsurg** [comment]
> I think this should be a GET request instead of a POST request. Why did you decide to go with POST?

I decided to go with `POST` for security reasons. Using `POST` instead of `GET` helps protect user login credentials, for example, username and password from being exposed in the URL and browser history, thereby reducing the risk of unauthorized access or data breaches.

**Comment by ijemmao** [comment]
@davydocsurg I see what you're saying, sounds good! looking forward to the PR on Tuesday~
