### ISSUE TITLE
Implement dashboard designs

### ISSUE THREAD

**Issue by davydocsurg** [nkowaokwu/igbo_api#753]
Implement dashboard designs

Link to design: 
https://www.figma.com/file/KEdhBREtlZKSXVMw95lZTg/Igbo-API-Editor-Platform?type=design&node-id=2001-1427&mode=design&t=Xsp7LtAhyEJmdpXA-0

**Comment by promiseNwafor** [comment]
@ijemmao I'd love to work on this

**Comment by ijemmao** [comment]
@promiseNwafor that's great! you can reach out to @davydocsurg since he's leading this ticket - would you like me to add you as an assignee?

**Comment by promiseNwafor** [comment]
Yea absolutely
