### ISSUE TITLE
Implement profile page designs

### ISSUE THREAD

**Issue by davydocsurg** [nkowaokwu/igbo_api#757]
Implement profile page designs

Link to design:
https://www.figma.com/file/KEdhBREtlZKSXVMw95lZTg/Igbo-API-Editor-Platform?type=design&node-id=2001-1427&mode=design&t=Xsp7LtAhyEJmdpXA-0

**Comment by Nedu** [comment]
@davydocsurg I would love to work on this ticket

**Comment by davydocsurg** [comment]
@Nedu  I'm already working on this. I'll more issues, stay tuned
