### ISSUE TITLE
Remove the `should` prefix from all unit tests titles

### ISSUE THREAD

**Issue by ijemmao** [nkowaokwu/igbo_api#779]
**Is your feature request related to a problem? Please describe.**
A good portion of our unit tests starts with the word `should` which is an unnecessary filler word. 

**Describe the solution you'd like**
Remove `should` from the beginning of our unit test names

**Describe alternatives you've considered**
N/A

**Additional context**
![image](https://github.com/nkowaokwu/igbo_api/assets/16169291/e0472d28-ec10-45a6-bf98-6470e1a8ef86)

**Comment by MohitKambli** [comment]
Hello,
Hope you're doing well.
I would like to work on this issue.

Thanks and Regards,
Mohit Kambli
