### ISSUE TITLE
Use code block for `style=no_style` code snippet in docs

### ISSUE THREAD

**Issue by ijemmao** [nkowaokwu/igbo_api#781]
**Describe the bug**
The code snippet for an example parameter for the Example route isn't using a code block and looks like plain text.

**To Reproduce**
1. Go to https://igboapi.com/docs/endpoints/examples
2. See the example code snippet not using a code block

**Expected behavior**
The style=no_style should be in a code block like `style=no_style`

**Screenshots**
![image](https://github.com/nkowaokwu/igbo_api/assets/16169291/bd2bb45a-eb5e-4749-81b8-be64470e4956)

**Comment by chidiadi01** [comment]
I'd love to work on this

**Comment by ijemmao** [comment]
@chidiadi01 I assigned you to this ticket!
