### ISSUE TITLE
Add IgboSpeech navigation option in nav bar

### ISSUE THREAD

**Issue by ijemmao** [nkowaokwu/igbo_api#800]
**Is your feature request related to a problem? Please describe.**
Nope, this is a feature request. We want to make the [IgboSpeech](https://speech.igboapi.com) more discoverable from the Igbo API website.

**Describe the solution you'd like**
Add "IgboSpeech" navigation option directly to the right of the "Research" option in the Igbo API navigation bar. The link should point to the IgboSpeech website: https://speech.igboapi.com.

Make sure to update existing tests to check for IgboSpeech. At least two test files should be updated after making this change.

**Describe alternatives you've considered**
N/A

**Additional context**
Ideal location for inserting IgboSpeech
![image](https://github.com/user-attachments/assets/30d22db6-b22b-4f30-b712-eeb2265d3837)

**Comment by vickywane** [comment]
@ijemmao I would love to work on this.

**Comment by ijemmao** [comment]
@vickywane all your's!

(other people are able to attempt this ticket as well)

**Comment by vickywane** [comment]
@ijemmao I want to pick up on this PR, finishing on the last changes made by @VarunHarish98. 

I tried running the project locally but I couldn't the `Database directory exists` error from the initialization scripts. 

Is there a guide that explains how to run the project locally?

**Comment by ijemmao** [comment]
@vickywane thanks for wanting to take on this issue!

However, this issue is no longer needed since we are preferring exposing the ASR technology that was shown in IgboSpeech via the Igbo API 

We have documentation that can help you with this. Specifically, this page should help: https://docs.igboapi.com/igbo_api/development
